# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, settings, inputs, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ba8daecb-c5d6-4dc9-bc51-a38b344ca6ed";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7FD3-5156";
    fsType = "vfat";
    # options = [ "fmask=0077" "dmask=0077" ];
    options = [ "rw" ];
  };

  swapDevices = [{
    device = "/dev/disk/by-uuid/d06b1b0e-01c1-4874-98af-9f8e2cc53b4e";
    # size = 4 * 1024; # Size in MB for a 4GB swap file
  }];

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/67F7388D1080E3AB";
    # fsType = "auto";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "nofail"
      "nodev"
      "uid=1000"
      "gid=1000"
      "utf8"
      "umask=022"
      "exec"
      "x-gvfs-show"
    ];
  };
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s16f1u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "${settings.system.architecture}";
  services = {
    # fstrim.enable = true;
    xserver.videoDrivers = settings.hardware.videoDrivers;
    # auto-epp.enable = true;
  };
  hardware = {
    uinput.enable = true;
    enableAllFirmware = true;
    cpu.amd.updateMicrocode = true;
    # cpu.amd.sev.enable = true;
    enableRedistributableFirmware = true;
    amdgpu.initrd.enable = true;
    amdgpu.amdvlk.enable = true;
    amdgpu.amdvlk.support32Bit.enable = true;
    amdgpu.amdvlk.supportExperimental.enable = true;
    amdgpu.opencl.enable = true;
    amdgpu.legacySupport.enable = false;
    amdgpu.amdvlk.settings = {
      IFH = 0;
      ShaderCacheMode = 1;
      EnableVmAlwaysValid = 1;
      IdleAfterSubmitGpuMask = 1;
      AllowVkPipelineCachingToDisk = 1;
    };
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        amdvlk
        mesa.opencl
        libvdpau-va-gl
        rocmPackages.clr
        rocmPackages.clr.icd
        rocmPackages.rocm-runtime
        rocmPackages.rocm-smi
        rocmPackages.rocminfo
        libGL
        libGLU
        libGLX
        libva
        libva-utils
        vaapiVdpau
      ];
      extraPackages32 = [
        pkgs.driversi686Linux.amdvlk
        #  pkgs.pkgsi686Linux.libva
      ];
    };
  };
  systemd.tmpfiles.rules = let
    rocmEnv = pkgs.symlinkJoin {
      name = "rocm-combined";
      paths = with pkgs.rocmPackages; [ rocblas hipblas clr ];
    };
  in [ "L+    /opt/rocm   -    -    -     -    ${rocmEnv}" ];

  environment.variables = {
    HIP_PATH = "${pkgs.rocmPackages.hip-common}/libexec/hip";

    # Load AMD driver for Xorg and Waylandard
    LIBVA_DRIVER_NAME = "amdgpu";
    VDPAU_DRIVER = "amdgpu";
    OCL_ICD_VENDORS = ''
      ${pkgs.rocmPackages.clr.icd}/etc/OpenCL/vendors/
    '';
    VK_ICD_FILENAMES = ''
      ${pkgs.amdvlk}/share/vulkan/icd.d/amd_icd64.json
    '';
    GPU_MAX_ALLOC_PERCENT = "50";
    GPU_MAX_HEAP_SIZE = "50";
    GPU_SINGLE_ALLOC_PERCENT = "50";
    GPU_MAX_USE_SYNC_OBJECTS = "1";
    GPU_FORCE_64BIT_PTR = "1";
    AMD_VULKAN_ICD = "RADV";
  };

  # We are creating the lact daemon service manually because the provided one hangs
  systemd.services.lactd = {
    enable = false;
    description = "Radeon GPU monitor";
    after = [ "syslog.target" "systemd-modules-load.service" ];

    unitConfig = { ConditionPathExists = "${pkgs.lact}/bin/lact"; };

    serviceConfig = {
      User = "root";
      ExecStart = "${pkgs.lact}/bin/lact daemon";
    };

    wantedBy = [ "multi-user.target" ];
  };

  # services.ucodenix = {
  #   enable = false;
  #   # docs: https://github.com/e-tho/ucodenix?tab=readme-ov-file#usage
  #   cpuModelId = "00A70F41";
  # };

  environment.systemPackages = with pkgs; [
    # xivlauncher # Custom launcher for FFXIV
    # zenstates # Linux utility for Ryzen processors and motherboards
    # amdgpu_top # Tool to display AMDGPU usage

    nvtopPackages.amd
    llvmPackages.mlir # Multi-Level IR Compiler Framework

    rocmPackages.hip-common
    rocmPackages.hipblas
    rocmPackages.hipcc
    rocmPackages.hipcub
    rocmPackages.hipfft
    rocmPackages.hipify
    rocmPackages.hiprand

    # zluda # ZLUDA - CUDA on Intel GPUs

    oclgrind # OpenCL device simulator and debugger
    amd-ucodegen # Tool to generate AMD microcode files
    microcode-amd # AMD Processor microcode patch
    microcodeAmd
    pciutils # Collection of programs for inspecting and manipulating configuration of PCI devices
    linux-firmware # Binary firmware collection packaged by kernel.org

    # AMD Stuff
    amdvlk # AMD Open Source Driver For Vulkan
    driversi686Linux.amdvlk # AMD Open Source Driver For Vulkan
    driversi686Linux.mesa # An open source 3D graphics library
    amdenc # AMD Encode Core Library
    amdctl # Set P-State voltages and clock speeds on recent AMD CPUs on Linux
    amd-blis # BLAS-compatible library optimized for AMD CPUs
    # amd-libflame # LAPACK-compatible linear algebra library optimized for AMD CPUs
    # amf # AMD's closed source Advanced Media Framework (AMF) driver
    aocl-utils # Interface to all AMD AOCL libraries to access CPU features

    clinfo # Print all known information about all available OpenCL platforms and devices in the system
    dxvk # A Vulkan-based translation layer for Direct3D
    glaxnimate # Simple vector animation program.
    glmark2 # OpenGL (ES) 2.0 benchmark
    gpu-viewer # A front-end to glxinfo, vulkaninfo, clinfo and es2_info
    hwdata # Hardware Database, including Monitors, pci.ids, usb.ids, and video cards
    khronos-ocl-icd-loader # Official Khronos OpenCL ICD Loader
    libdrm # Direct Rendering Manager library and headers
    libplacebo # Reusable library for GPU-accelerated video/image rendering primitives
    libva # An implementation for VA-API (Video Acceleration API)
    mesa # An open source 3D graphics library
    mesa_glu # OpenGL utility library
    mesa_i686 # Open source 3D graphics library
    mesa-demos # Collection of demos and test programs for OpenGL and Mesa
    ocl-icd # OpenCL ICD Loader for opencl-headers-2023.12.14
    openal # OpenAL alternative
    opencl-clang # A clang wrapper library with an OpenCL-oriented API and the ability to compile OpenCL C kernels to SPIR-V modules
    opencl-clhpp # OpenCL Host API C++ bindings
    opencl-headers # Khronos OpenCL headers version 2023.12.14
    oclgrind # OpenCL device simulator and debugger

    vkbasalt # Vulkan post processing layer for Linux
    vkquake # Vulkan Quake port based on QuakeSpasm
    vulkan-extension-layer # Layers providing Vulkan features when native support is unavailable
    vulkan-headers # Vulkan Header files and API registry
    vulkan-tools # Khronos official Vulkan Tools and Utilities
    vulkan-utility-libraries # Set of utility libraries for Vulkan

    xorg.xf86videoamdgpu

    lact # Linux AMDGPU Controller and GPU overclocking tool
  ];
}
