source 'https://rubygems.org'
ruby '3.4.7'

gem 'activesupport', require: false
gem 'html-pipeline'
gem 'nokogiri', '>= 1.15'
gem 'rake'
gem 'terminal-table'
gem 'thor'
gem 'typhoeus'
gem 'yajl-ruby', require: false

group :app do
  gem 'browser'
  gem 'chunky_png'
  gem 'erubi'
  gem 'image_optim'
  gem 'rack-ssl-enforcer'
  gem 'rack'
  gem 'rss'
  gem 'sass'
  gem 'sinatra'
  gem 'sinatra-contrib'
  gem 'sprockets'
  gem 'sprockets-helpers'
  gem 'sprockets-sass'
end

group :development do
  gem 'debug'
  gem 'pry'
  gem 'better_errors'
end

group :production do
  gem 'newrelic_rpm'
  gem 'terser'
end

group :docs do
  gem 'progress_bar', require: false
  gem 'redcarpet'
  gem 'tty-pager', require: false
  gem 'unix_utils', require: false
end

group :test do
  gem 'minitest'
  gem 'rack-test', require: false
  gem 'rr', require: false
end
