# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, mySettings, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "ohci_pci"
    "ehci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "radeon"
  ];
  boot.initrd.kernelModules = [ "amdgpu" "radeon" ];
  boot.kernelModules = [ "fuse" "kvm-amd" "coretemp" ];
  boot.blacklistedKernelModules = [ "k10temp" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ rtl8812au ];
  boot.kernelParams = [
    "amd_pstate=active"
    # for Southern Islands (SI i.e. GCN 1) cards
    # "radeon.si_support=0"
    # "amdgpu.si_support=1"
    # for Sea Islands (CIK i.e. GCN 2) cards
    "radeon.cik_support=0"
    "amdgpu.cik_support=1"

    "amdgpu.dc=1"
    "amdgpu.dpm=1"
    "amdgpu.gpu_recovery=1"
    # "amdgpu.runpm=0"
    # "amdgpu.gttsize=4096"
    "amdgpu.ppfeaturemask=0xffffffff"
    # "amdgpu.deep_color=1"
    # "amdgpu.vm_size=8"
    # "amdgpu.exp_hw_support=1"
    # "amdgpu.vm_fragment_size=9"
    # "amdgpu.vm_fault_stop=2"
    # "amdgpu.vm_update_mode=3"
    # "amdgpu.unified_memory=1"
    # "amdgpu.memory_alloc_mode=2"
  ];

  # services.fstrim.enable = true;
  services.xserver.videoDrivers =
    [ "amdgpu" ]; # "displaylink" "modesetting" "amdgpu"

  hardware = {
    amdgpu.amdvlk.enable = true;
    amdgpu.amdvlk.support32Bit.enable = true;
    amdgpu.amdvlk.supportExperimental.enable = true;
    amdgpu.initrd.enable = false;
    amdgpu.opencl.enable = true;
    amdgpu.legacySupport.enable = true;
    # cpu.amd.updateMicrocode = true;
    enableAllFirmware = true;
    amdgpu.amdvlk.settings = {
      AllowVkPipelineCachingToDisk = 1;
      EnableVmAlwaysValid = 1;
      IFH = 0;
      IdleAfterSubmitGpuMask = 1;
      ShaderCacheMode = 1;
    };
    graphics = {
      enable = true;
      enable32Bit = true;
      # To enable Vulkan support for 32-bit applications, also add:
      extraPackages = with pkgs; [ mesa.opencl amdvlk rocmPackages.clr.icd ];
      extraPackages32 = [ pkgs.driversi686Linux.amdvlk ];
    };
  };

  systemd.tmpfiles.rules = let
    rocmEnv = pkgs.symlinkJoin {
      name = "rocm-combined";
      paths = with pkgs.rocmPackages; [ rocblas hipblas clr ];
    };
  in [ "L+    /opt/rocm   -    -    -     -    ${rocmEnv}" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ba8daecb-c5d6-4dc9-bc51-a38b344ca6ed";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7FD3-5156";
    fsType = "vfat";
    # options = [ "fmask=0077" "dmask=0077" ];
    options = [ "rw" ];

  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/d06b1b0e-01c1-4874-98af-9f8e2cc53b4e"; }];

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/67F7388D1080E3AB";
    fsType = "auto";
    options = [
      "nofail"
      "nodev"
      "uid=1000"
      "gid=1000"
      "utf8"
      "umask=022"
      "exec"
      "x-gvfs-show"
    ];
  };
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s16f1u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "${mySettings.system}";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  environment.variables = {
    # For AMD GPUs
    OCL_ICD_VENDORS = ''
      ${pkgs.rocmPackages.clr.icd}/etc/OpenCL/vendors/
    '';
    VK_ICD_FILENAMES = ''
      ${pkgs.amdvlk}/share/vulkan/icd.d/amd_icd64.json
    '';
    GPU_MAX_ALLOC_PERCENT = "50";
    GPU_MAX_HEAP_SIZE = "50";
    GPU_SINGLE_ALLOC_PERCENT = "50";
    GPU_MAX_USE_SYNC_OBJECTS = "1";
    GPU_FORCE_64BIT_PTR = "1";
    AMD_VULKAN_ICD = "RADV";
  };

  environment.systemPackages = with pkgs; [

    oclgrind # OpenCL device simulator and debugger
    amd-ucodegen # Tool to generate AMD microcode files
    microcode-amd # AMD Processor microcode patch
    pciutils # Collection of programs for inspecting and manipulating configuration of PCI devices
    linux-firmware # Binary firmware collection packaged by kernel.org
    # AMD Stuff
    amdvlk # AMD Open Source Driver For Vulkan
    driversi686Linux.amdvlk # AMD Open Source Driver For Vulkan
    driversi686Linux.mesa # An open source 3D graphics library
    amdenc # AMD Encode Core Library
    amdctl # Set P-State voltages and clock speeds on recent AMD CPUs on Linux
    amd-blis # BLAS-compatible library optimized for AMD CPUs
    amd-libflame # LAPACK-compatible linear algebra library optimized for AMD CPUs
    amf # AMD's closed source Advanced Media Framework (AMF) driver
    aocl-utils # Interface to all AMD AOCL libraries to access CPU features

    clinfo # Print all known information about all available OpenCL platforms and devices in the system
    dxvk # A Vulkan-based translation layer for Direct3D
    glaxnimate # Simple vector animation program.
    glmark2 # OpenGL (ES) 2.0 benchmark
    gpu-viewer # A front-end to glxinfo, vulkaninfo, clinfo and es2_info
    hwdata # Hardware Database, including Monitors, pci.ids, usb.ids, and video cards
    khronos-ocl-icd-loader # Official Khronos OpenCL ICD Loader
    libdrm # Direct Rendering Manager library and headers
    libplacebo # Reusable library for GPU-accelerated video/image rendering primitives
    libva # An implementation for VA-API (Video Acceleration API)
    libva-utils # A collection of utilities and examples for VA-API
    mesa # An open source 3D graphics library
    mesa_glu # OpenGL utility library
    mesa_i686 # Open source 3D graphics library
    mesa-demos # Collection of demos and test programs for OpenGL and Mesa
    ocl-icd # OpenCL ICD Loader for opencl-headers-2023.12.14
    openal # OpenAL alternative
    opencl-clang # A clang wrapper library with an OpenCL-oriented API and the ability to compile OpenCL C kernels to SPIR-V modules
    opencl-clhpp # OpenCL Host API C++ bindings
    opencl-headers # Khronos OpenCL headers version 2023.12.14
    oclgrind # OpenCL device simulator and debugger

    vkbasalt # Vulkan post processing layer for Linux
    vkquake # Vulkan Quake port based on QuakeSpasm
    vulkan-extension-layer # Layers providing Vulkan features when native support is unavailable
    vulkan-headers # Vulkan Header files and API registry
    vulkan-tools # Khronos official Vulkan Tools and Utilities
    vulkan-utility-libraries # Set of utility libraries for Vulkan

    xorg.xf86videoamdgpu

    # lact # Linux AMDGPU Controller
    corectrl # Control your computer hardware via application profiles

    rocmPackages.hipcc
    rocmPackages.hip-common
    rocmPackages.hiprand
    rocmPackages.hipblas
    rocmPackages.hipfft
    rocmPackages.hipcub
    rocmPackages.hipify
  ];
}
