# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # services.fstrim.enable = true;

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "ohci_pci"
    "ehci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "radeon"
  ];
  boot.initrd.kernelModules = [ "amdgpu" "radeon" ];
  boot.kernelModules = [ "fuse" "kvm-amd" "coretemp" ];
  boot.blacklistedKernelModules = [ "k10temp" ];
  boot.kernelParams = [ "amd_pstate=active" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ rtl8812au ];
  boot.loader.kernelParams = [
    # for Southern Islands (SI i.e. GCN 1) cards
    "radeon.si_support=0"
    "amdgpu.si_support=1"

    # for Sea Islands (CIK i.e. GCN 2) cards
    "radeon.cik_support=0"
    "amdgpu.cik_support=1"

    "amdgpu.dc=1"
    "amdgpu.dpm=1"
    "amdgpu.gpu_recovery=1"
    # "amdgpu.runpm=0"
    # "amdgpu.gttsize=4096"
    "amdgpu.ppfeaturemask=0xffffffff"
    # "amdgpu.deep_color=1"
    # "amdgpu.vm_size=8"
    # "amdgpu.exp_hw_support=1"
    # "amdgpu.vm_fragment_size=9"
    # "amdgpu.vm_fault_stop=2"
    # "amdgpu.vm_update_mode=3"
    # "amdgpu.unified_memory=1"
    # "amdgpu.memory_alloc_mode=2"
  ];

  environment.systemPackages = with pkgs.rocmPackages; [
    hipcc
    hip-common
    hiprand
    hipblas
    hipfft
    hipcub
    hipify
  ];

  services.xserver.videoDrivers = [ "modesetting" ];

  hardware.graphics = {
    enable = true;
    extraPackages = [ pkgs.rocmPackages.clr.icd ];
    extraPackages32 = [ ];
    enable32Bit = true;
  };

  hardware.amdgpu.initrd.enable = true;
  hardware.amdgpu.opencl.enable = true;
  hardware.amdgpu.amdvlk.enable = true;

  systemd.tmpfiles.rules = let
    rocmEnv = pkgs.symlinkJoin {
      name = "rocm-combined";
      paths = with pkgs.rocmPackages; [ rocblas hipblas clr ];
    };
  in [ "L+    /opt/rocm   -    -    -     -    ${rocmEnv}" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ba8daecb-c5d6-4dc9-bc51-a38b344ca6ed";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7FD3-5156";
    fsType = "vfat";
    # options = [ "fmask=0077" "dmask=0077" ];
    options = [ "rw" ];

  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/d06b1b0e-01c1-4874-98af-9f8e2cc53b4e"; }];

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/67F7388D1080E3AB";
    fsType = "auto";
    options = [
      "nofail"
      "nodev"
      "uid=1000"
      "gid=1000"
      "utf8"
      "umask=022"
      "exec"
      "x-gvfs-show"
    ];
  };
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s16f1u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
