# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, settings, inputs, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.initrd.availableKernelModules =
    [ "ahci" "ohci_pci" "ehci_pci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/253b308e-f703-4da9-8116-d9bc6c38b69a";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1459-5ECF";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  fileSystems."/home/softeng/windows" = {
    device = "//192.168.1.3/windows_shared";
    fsType = "cifs";
    options = [
      "username=win"
      "password=1122"
      "uid=1000"
      "gid=100"
      "iocharset=utf8"
      "file_mode=0775"
      "dir_mode=0775"
      "rw"
      "nofail"
      "nounix"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/67F7388D1080E3AB";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "nofail"
      "nodev"
      "uid=1000"
      "gid=1000"
      "utf8"
      "umask=022"
      "exec"
      "x-gvfs-show"
    ];
  };

  # Don't Forget To Change The Owner of The Partition If Needed.
  # sudo chown -R softeng:wheel /data2
  #  fileSystems."/data2" = {
  #    device = "/dev/disk/by-uuid/4f2e4b65-d0c5-413b-9558-c210008c5657";
  #    fsType = "xfs";
  #    options = [
  #      "rw"
  #      "nofail"
  #      "nodev"
  #      "uid=1000"
  #      "gid=1000"
  #      "utf8"
  #      "umask=022"
  #      "exec"
  #      "x-gvfs-show"
  #    ];
  #  };

  #  swapDevices = [{
  # device = "/dev/disk/by-uuid/d06b1b0e-01c1-4874-98af-9f8e2cc53b4e";
  # size = 4 * 1024; # Size in MB for a 4GB swap file
  # }];
}
