# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, settings, inputs, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.initrd.availableKernelModules =
    [ "ahci" "ohci_pci" "ehci_pci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/253b308e-f703-4da9-8116-d9bc6c38b69a";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1459-5ECF";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  fileSystems."/home/softeng/windows" = {
    device = "//192.168.1.3/windows_shared";
    fsType = "cifs";
    options = [
      "username=win"
      "password=1122"
      "uid=1000"
      "gid=100"
      "iocharset=utf8"
      "file_mode=0775"
      "dir_mode=0775"
      "rw"
      "nofail"
      "nounix"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/67F7388D1080E3AB";
    fsType = "ntfs-3g"; # if NTFS
    # fsType = "btrfs";
    options = [ # With Option-by-Option Explanation
      # This only for BTRFS
      # "defaults" # Enables default options: rw, suid, dev, exec, auto, nouser, and async.
      # "compress=zstd" # Btrfs only – enables compression using zstd algorithm (saves space and may improve performance).
      # "nodev" # Don’t allow device files on this mount (security measure).

      # This only for NTFS
      "uid=1000" # NTFS/ntfs-3g only – set default file ownership to user ID 1000 (your user).
      "gid=1000" # NTFS/ntfs-3g only – set default group to group ID 1000.
      "utf8" # NTFS/ntfs-3g only – interpret file names as UTF-8.
      "umask=022" # NTFS/ntfs-3g only – sets default permission mask (directories = 755, files = 644).

      # For Both File System
      "rw" # Mount the filesystem as read-write.
      "nofail" # Don’t fail boot if this mount fails (useful for external or optional drives).
      "exec" # Allow executing binaries from this mount.
      "x-gvfs-show" # Makes the mount point visible in GNOME/Nautilus (GVFS). Optional aesthetic.
    ];
  };

  # Don't Forget To Change The Owner of The Partition If Needed.
  # sudo chown -R softeng:wheel /data2
  #  fileSystems."/data2" = {
  #    device = "/dev/disk/by-uuid/4f2e4b65-d0c5-413b-9558-c210008c5657";
  #    fsType = "xfs";
  #    options = [
  #      "rw"
  #      "nofail"
  #      "nodev"
  #      "uid=1000"
  #      "gid=1000"
  #      "utf8"
  #      "umask=022"
  #      "exec"
  #      "x-gvfs-show"
  #    ];
  #  };

  #  swapDevices = [{
  # device = "/dev/disk/by-uuid/d06b1b0e-01c1-4874-98af-9f8e2cc53b4e";
  # size = 4 * 1024; # Size in MB for a 4GB swap file
  # }];
}
